const UserActionTypes = {
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
  UPDATE_USERS_LIST: "UPDATE_USERS_LIST",
};

export default UserActionTypes;
